### ISSUE TITLE
Hey, care to help me out with this? I really think this plugin is awesome, but it won't turn on for me...

### ISSUE THREAD

**Issue by DeathRavn359** [PocketEssential/UltraFaction#12] opened 2018-08-11 20:26 UTC
### Issue description
Plugin crashes on load.

### Steps to reproduce the issue
I started my server and it would not turn on.

### OS and versions
> * UltraFaction Version: Dev build #15 (&BA34)
> * Server Software: PocketMine-MP 
> * Machine OS: Mac OSX

### Crashdump, console erros or other info
```
11.08 16:22:31 [Server] Server thread/INFO Enabling UltraFaction v1.0.2
11.08 16:22:31 [Server] Server thread/INFO --------------------------------------
11.08 16:22:31 [Server] Server thread/INFO -           ULTRA FACTION             
11.08 16:22:31 [Server] Server thread/INFO -  
11.08 16:22:31 [Server] Server thread/INFO -  Language: eng
11.08 16:22:31 [Server] Server thread/INFO -  Loaded a total of: 2 factions!
11.08 16:22:31 [Server] Server thread/INFO -  Data Provider: json
11.08 16:22:31 [Server] Server thread/INFO -  Enjoy and stay flexing!
11.08 16:22:31 [Server] Server thread/INFO --------------------------------------
11.08 16:22:31 [Server] Server thread/CRITICAL ErrorException: "Undefined index: Roles" (EXCEPTION) in "UltraFaction-master 5/src/xZeroMCPE/UltraFaction/Faction/FactionManager" at line 42
11.08 16:22:31 [Server] Server thread/DEBUG #0 UltraFaction-master 5/src/xZeroMCPE/UltraFaction/Faction/FactionManager(42): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string Undefined index: Roles, string /plugins/UltraFaction-master 5/src/xZeroMCPE/UltraFaction/Faction/FactionManager.php, integer 42, array Array())
11.08 16:22:31 [Server] Server thread/DEBUG #1 UltraFaction-master 5/src/xZeroMCPE/UltraFaction/Faction/FactionManager(29): xZeroMCPE\UltraFaction\Faction\FactionManager->loadRequired()
11.08 16:22:31 [Server] Server thread/DEBUG #2 UltraFaction-master 5/src/xZeroMCPE/UltraFaction/UltraFaction(67): xZeroMCPE\UltraFaction\Faction\FactionManager->__construct()
11.08 16:22:31 [Server] Server thread/DEBUG #3 UltraFaction-master 5/src/xZeroMCPE/UltraFaction/UltraFaction(45): xZeroMCPE\UltraFaction\UltraFaction->loadComponents()
11.08 16:22:31 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/PluginBase(111): xZeroMCPE\UltraFaction\UltraFaction->onEnable()
11.08 16:22:31 [Server] Server thread/DEBUG #5 src/pocketmine/plugin/PluginManager(613): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
11.08 16:22:31 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1927): pocketmine\plugin\PluginManager->enablePlugin(xZeroMCPE\UltraFaction\UltraFaction object)
11.08 16:22:31 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1913): pocketmine\Server->enablePlugin(xZeroMCPE\UltraFaction\UltraFaction object)
11.08 16:22:31 [Server] Server thread/DEBUG #8 src/pocketmine/Server(1707): pocketmine\Server->enablePlugins(integer 1)
11.08 16:22:31 [Server] Server thread/DEBUG #9 src/pocketmine/PocketMine(243): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
11.08 16:22:31 [Server] Server thread/DEBUG #10 /pmmp_1261_1.5.0.phar(1): require(string phar:///pmmp_1261_1.5.0.phar/src/pocketmine/PocketMine.php)
```

SIDE NOTE: Yes... I understand this plugin is yet to be finished.

**Comment by xZeroMCPE** [comment] 2018-08-11 21:06
@DeathRavn359 Weird, unable to reproduce. What does your `Factions.json` look like?

EDIT: Make sure you're on the latest of UltraFactions and try again with a clean installation!

**Comment by DeathRavn359** [comment] 2018-08-11 21:33
Thank you! I'm testing it out now!

**Comment by xZeroMCPE** [comment] 2018-08-11 21:38
Great, let me know if you encounter any issues.

**Comment by DeathRavn359** [comment] 2018-08-11 21:57
Hey, I don't know if this should be a separate issue or not, but whenever a player is invited to a  faction and they accept, an unknown error occurs to the player and on the console it says this:

```
11.08 17:59:20 [Server] Server thread/CRITICAL Unhandled exception executing command 'f accept' in f: Undefined index: dirven350
11.08 17:59:20 [Server] Server thread/CRITICAL ErrorException: "Undefined index: dirven350" (EXCEPTION) in "UltraFaction (2).phar/src/xZeroMCPE/UltraFaction/Faction/FactionManager" at line 52
11.08 17:59:20 [Server] Server thread/DEBUG #0 UltraFaction (2).phar/src/xZeroMCPE/UltraFaction/Faction/FactionManager(52): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string Undefined index: dirven350, string phar:///plugins/UltraFaction (2).phar/src/xZeroMCPE/UltraFaction/Faction/FactionManager.php, integer 52, array Array())
11.08 17:59:20 [Server] Server thread/DEBUG #1 UltraFaction (2).phar/src/xZeroMCPE/UltraFaction/Command/Types/F(186): xZeroMCPE\UltraFaction\Faction\FactionManager->getFaction(pocketmine\Player object)
11.08 17:59:20 [Server] Server thread/DEBUG #2 src/pocketmine/command/SimpleCommandMap(258): xZeroMCPE\UltraFaction\Command\Types\F->execute(pocketmine\Player object, string f, array Array())
11.08 17:59:20 [Server] Server thread/DEBUG #3 src/pocketmine/Server(1954): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string f accept)
11.08 17:59:20 [Server] Server thread/DEBUG #4 src/pocketmine/Player(2192): pocketmine\Server->dispatchCommand(pocketmine\Player object, string f accept)
11.08 17:59:20 [Server] Server thread/DEBUG #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(222): pocketmine\Player->chat(string /f accept)
11.08 17:59:20 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
11.08 17:59:20 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
11.08 17:59:20 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/protocol/BatchPacket(114): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
11.08 17:59:20 [Server] Server thread/DEBUG #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
11.08 17:59:20 [Server] Server thread/DEBUG #10 src/pocketmine/Player(3057): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
11.08 17:59:20 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/RakLibInterface(158): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
11.08 17:59:20 [Server] Server thread/DEBUG #12 vendor/pocketmine/raklib/src/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 72.28.176.43 36613, raklib\protocol\EncapsulatedPacket object, integer 0)
11.08 17:59:20 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/RakLibInterface(103): raklib\server\ServerHandler->handlePacket()
11.08 17:59:20 [Server] Server thread/DEBUG #14 src/pocketmine/network/Network(94): pocketmine\network\mcpe\RakLibInterface->process()
11.08 17:59:20 [Server] Server thread/DEBUG #15 src/pocketmine/network/mcpe/RakLibInterface(80): pocketmine\network\Network->processInterface(pocketmine\network\mcpe\RakLibInterface object)
11.08 17:59:20 [Server] Server thread/DEBUG #16 vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
11.08 17:59:20 [Server] Server thread/DEBUG #17 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
11.08 17:59:20 [Server] Server thread/DEBUG #18 src/pocketmine/Server(2257): pocketmine\snooze\SleeperHandler->sleepUntil(double 1534024760.3195)
11.08 17:59:20 [Server] Server thread/DEBUG #19 src/pocketmine/Server(2128): pocketmine\Server->tickProcessor()
11.08 17:59:20 [Server] Server thread/DEBUG #20 src/pocketmine/Server(1709): pocketmine\Server->start()
11.08 17:59:20 [Server] Server thread/DEBUG #21 src/pocketmine/PocketMine(243): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
11.08 17:59:20 [Server] Server thread/DEBUG #22 /pmmp_1261_1.5.0.phar(1): require(string phar:///pmmp_1261_1.5.0.phar/src/pocketmine/PocketMine.php)
```

(dirven350 is my username, and this happened when trying to join a faction.)

**Comment by xZeroMCPE** [comment] 2018-08-11 22:17
Should be fixed on the latest patched.

**Comment by DeathRavn359** [comment] 2018-08-11 22:46
Words cannot describe how thankful I am, my players love it!

**Comment by DeathRavn359** [comment] 2018-08-11 23:01
Owch!

```
11.08 19:05:04 [Server] Server thread/CRITICAL Unhandled exception executing command 'f create OpSkillZ' in f: Undefined index: Broadcast faction creation
11.08 19:05:04 [Server] Server thread/CRITICAL ErrorException: "Undefined index: Broadcast faction creation" (EXCEPTION) in "UltraFaction (3).phar/src/xZeroMCPE/UltraFaction/Command/Types/F" at line 87
11.08 19:05:04 [Server] Server thread/DEBUG #0 UltraFaction (3).phar/src/xZeroMCPE/UltraFaction/Command/Types/F(87): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string Undefined index: Broadcast faction creation, string phar:///plugins/UltraFaction (3).phar/src/xZeroMCPE/UltraFaction/Command/Types/F.php, integer 87, array Array())
11.08 19:05:04 [Server] Server thread/DEBUG #1 src/pocketmine/command/SimpleCommandMap(258): xZeroMCPE\UltraFaction\Command\Types\F->execute(pocketmine\Player object, string f, array Array())
11.08 19:05:04 [Server] Server thread/DEBUG #2 src/pocketmine/Server(1971): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string f create OpSkillZ)
11.08 19:05:04 [Server] Server thread/DEBUG #3 src/pocketmine/Player(1966): pocketmine\Server->dispatchCommand(pocketmine\Player object, string f create OpSkillZ)
11.08 19:05:04 [Server] Server thread/DEBUG #4 src/pocketmine/network/mcpe/handler/SimpleSessionHandler(84): pocketmine\Player->chat(string ./f create OpSkillZ)
11.08 19:05:04 [Server] Server thread/DEBUG #5 src/pocketmine/network/mcpe/protocol/TextPacket(128): pocketmine\network\mcpe\handler\SimpleSessionHandler->handleText(pocketmine\network\mcpe\protocol\TextPacket object)
11.08 19:05:04 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/NetworkSession(170): pocketmine\network\mcpe\protocol\TextPacket->handle(pocketmine\network\mcpe\handler\SimpleSessionHandler object)
11.08 19:05:04 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/NetworkSession(155): pocketmine\network\mcpe\NetworkSession->handleDataPacket(pocketmine\network\mcpe\protocol\TextPacket object)
11.08 19:05:04 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/RakLibInterface(143): pocketmine\network\mcpe\NetworkSession->handleEncoded(string x...d``d.qJLqO.M-2204a`...OSH.JM,IU./.......02566275022.0636d......)
11.08 19:05:04 [Server] Server thread/DEBUG #9 vendor/pocketmine/raklib/src/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 24.130.95.88 52756, raklib\protocol\EncapsulatedPacket object, integer 0)
11.08 19:05:04 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/RakLibInterface(97): raklib\server\ServerHandler->handlePacket()
11.08 19:05:04 [Server] Server thread/DEBUG #11 src/pocketmine/network/Network(91): pocketmine\network\mcpe\RakLibInterface->process()
11.08 19:05:04 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/RakLibInterface(74): pocketmine\network\Network->processInterface(pocketmine\network\mcpe\RakLibInterface object)
11.08 19:05:04 [Server] Server thread/DEBUG #13 vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
11.08 19:05:04 [Server] Server thread/DEBUG #14 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
11.08 19:05:04 [Server] Server thread/DEBUG #15 src/pocketmine/Server(2275): pocketmine\snooze\SleeperHandler->sleepUntil(double 1534028704.7488)
11.08 19:05:04 [Server] Server thread/DEBUG #16 src/pocketmine/Server(2146): pocketmine\Server->tickProcessor()
11.08 19:05:04 [Server] Server thread/DEBUG #17 src/pocketmine/Server(1724): pocketmine\Server->start()
11.08 19:05:04 [Server] Server thread/DEBUG #18 src/pocketmine/PocketMine(243): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
11.08 19:05:04 [Server] Server thread/DEBUG #19 /pmmp_1318_1.5.0.phar(1): require(string phar:///pmmp_1318_1.5.0.phar/src/pocketmine/PocketMine.php)
```

**Comment by xZeroMCPE** [comment] 2018-08-11 23:06
Weird works fine for me. Double check `config.json` exists, and try again.

**Comment by DeathRavn359** [comment] 2018-08-11 23:50
Hey, ah, this is my config...
            "Friendly Fire": false
But players can still hit each other...

No errors.

**Comment by xZeroMCPE** [comment] 2018-08-11 23:57
Again, works fine for me. Check to see if there's a plugin that's maybe causing that?

Anyhow, closing this issue as it's been solved. Open another one if you found any bugs, be sure you WELL tested it!

**Closed as completed by xZeroMCPE** 2018-08-11 23:57 UTC
